name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install backend dependencies
      working-directory: ./Backend
      run: npm install

    - name: Install frontend dependencies
      working-directory: ./Client
      run: npm install

    - name: Build frontend
      working-directory: ./Client
      run: npm run build

    - name: Run backend tests
      working-directory: ./Backend
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      run: |
        ssh root@srv548325 << 'EOF'
          cd /var/www/Swargadhi-Web/Backend && git pull origin main && npm install
          pm2 restart all

          cd /var/www/Swargadhi-Web/Client && git pull origin main && npm install && npm run build
          pm2 restart all
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
