name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Update and build the backend
          cd /var/www/Swargadhi-Web/Backend
          git pull origin main
          npm install --force
          pm2 restart all

          # Update and build the client
          cd /var/www/Swargadhi-Web/Client
          git pull origin main
          npm install --force
          npm run build
